name: Run Kubeflow Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # This step needs to be adjusted to work in GitHub Actions
      # Ensure Kubeflow is accessible from the Actions runner environment
      - name: Verify Kubeflow connection
        run: |
          curl http://127.0.0.1:8080/apis/v1beta1/healthz

      # Ensure kubeflow.py is correctly configured and executable
      - name: Run pipeline
        run: |
          python kubeflow.py
        # Optionally, use GitHub Secrets for sensitive info and environment variables
        env:
          KUBEFLOW_ENDPOINT: ${{ secrets.KUBEFLOW_ENDPOINT }}
          KUBEFLOW_API_KEY: ${{ secrets.KUBEFLOW_API_KEY }}
 
