name: Run Kubeflow Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl

      - name: Configure kubectl
        run: |
          kubectl config set-cluster my-cluster --server=https://YOUR_CLUSTER_SERVER
          kubectl config set-credentials my-user --token=${{ secrets.KUBE_TOKEN }}
          kubectl config set-context my-context --cluster=my-cluster --user=my-user
          kubectl config use-context my-context

      - name: Port forward ml-pipeline service
        run: |
           kubectl port-forward -n kubeflow svc/ml-pipeline-ui 8080:80 --address 0.0.0.0 & sleep 15  # Increase sleep if necessary


      - name: Verify Kubeflow connection
        run: |
          curl http://localhost:8080/apis/v1beta1/healthz

      - name: Run pipeline
        run: |
          python kubeflow.py
        env:
          KUBEFLOW_ENDPOINT: http://localhost:8080
          KUBEFLOW_API_KEY: ${{ secrets.KUBEFLOW_API_KEY }}
